language: c
os: linux
dist: bionic
addons:
  apt:
    update: true
    packages:
    - git
    - build-essential
    - python-dev
    - python-gtk2-dev
    - make
    - autoconf
    - libgtk2.0-dev
    - libwxgtk3.0-dev
    - libjson-c-dev
    - libjson-glib-dev
    - gtk-doc-tools
    - intltool
    - libgirepository1.0-dev
    - asciidoc
    - libsuitesparse-dev
    - libumfpack5
    - libopenexr-dev
    - libspiro-dev
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libwebp-dev
    - libgexiv2-dev
    - libraw-dev
    - librsvg2-dev
    - python-cairo-dev
    - libpoppler-glib-dev
    - libbz2-1.0
    - cmake-extras
    - libbz2-dev
    - libwebkitgtk-dev
    - libgs-dev
    - libopenjp2-7-dev
    - libmng-dev
    - libheif-dev
    - libwmf-dev
    - libxpm-dev
    - xvfb
    - gnome-icon-theme
    - llvm
    - autopoint
    - flatpak
env:
- INSTALL_PREFIX=$TRAVIS_BUILD_DIR/glimpse-prefix SRC_PREFIX=$TRAVIS_BUILD_DIR PATH=$INSTALL_PREFIX/bin:$PATH
  PKG_CONFIG_PATH=$INSTALL_PREFIX/lib/pkgconfig:$INSTALL_PREFIX/lib/x86_64-linux-gnu/pkgconfig:$INSTALL_PREFIX/share/pkgconfig:$PKG_CONFIG_PATH
  LD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$INSTALL_PREFIX/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
  ACLOCAL_FLAGS="-I $INSTALL_PREFIX/share/aclocal $ACLOCAL_FLAGS"
before_install:
- mkdir -p $INSTALL_PREFIX/share/aclocal
- git submodule update --init
script:
- cd $SRC_PREFIX/babl
- "./autogen.sh --prefix=$INSTALL_PREFIX"
- make && make install
- cd $SRC_PREFIX/mypaint-brushes
- "./autogen.sh --prefix=$INSTALL_PREFIX"
- "./configure --prefix=$INSTALL_PREFIX"
- make && make install
- cd $SRC_PREFIX/libmypaint
- "./autogen.sh --prefix=$INSTALL_PREFIX"
- "./configure --prefix=$INSTALL_PREFIX"
- make && make install
- cd $SRC_PREFIX/gegl
- "./autogen.sh --prefix=$INSTALL_PREFIX"
- make && make install
- cd $SRC_PREFIX
- "./autogen.sh --prefix=$INSTALL_PREFIX"
- make && make install
before_deploy:
- tar -zcvf glimpse-linux-test.tar.gz glimpse-prefix/
deploy:
  provider: releases
  api_key:
    secure: hV92pKcVFNJQoC7tQH9s6XX9vtIeR/lrYOzP2g4QtsDpgCNFnpQ2b9e2SWSx43PzPpwydVfHVojFxEvA2wc44hR4RHX/4WaHvO+Zc/8aQzXZDWgSR++MGvHwZxoZVNq0s5xTvUT+pdsjIOduJ0Ke8A9GHhE4+NLe4uP21VTPIt/5tVMdxGAqcE6BNVo7AjPsSpoXK8BLEvir+N7l+HsSaUoLBhjlTYs3jT6f7XvdWVJzhv31ODLfL/AxHJE859MhNNVP2befJQh1aDasuehr83Ccl4gK+xonTOBJFvK8FwFQb8GV5so3Pj19rj0QGOjLq2uae1cg6p912WZwvKDyBf1kQ3CINNThXUt+buCNOCEwgEdQcB8gOfQexGyEUPWzPtgeSOP2k+FblOuF0YjUUSu1MD7YJmeA+57OeyUPKevq3YiCxxqCst/tIX0zNsciFkjQYa18/OH+3F9zTO/42Ae0hLHo7nwzPNzNJSaI8w/uM5v0ACqACQlJ3acyXn+xgWIrFScVUj0sZX2KIWG85iNmV9eyM6rV9yXhM1Uio1K45bKr3r992gH7L1aQ9Popm6fyeO730t4t8nBjRA2371BHXvRLUGEVpK2CeGoErO5YE8HaCR5F1dy2gaep95QqNoOG4EiWksjVEXoCd0He9ffbCbAPhSh1A4GxKTkqU7o=
  file: glimpse-linux-test.tar.gz
  skip_cleanup: true
  draft: true
  on:
    repo: glimpse-editor/Glimpse
    branch: travis-ci
